// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8-0trzKY-2h9oQ5kBn367DtOk-IXiL70',
    appId: '1:414511917724:web:3f6ca3bbe9882de3cedb59',
    messagingSenderId: '414511917724',
    projectId: 'fire-98df0',
    authDomain: 'fire-98df0.firebaseapp.com',
    storageBucket: 'fire-98df0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXWaHBgD1FymaM5-AT0vIJlVRo2fpx7ts',
    appId: '1:414511917724:android:7ac5bc11498e11b3cedb59',
    messagingSenderId: '414511917724',
    projectId: 'fire-98df0',
    storageBucket: 'fire-98df0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJFgE_a0E60szJ5TurUKiShA-mTOcTggg',
    appId: '1:414511917724:ios:e72f246d89601e48cedb59',
    messagingSenderId: '414511917724',
    projectId: 'fire-98df0',
    storageBucket: 'fire-98df0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJFgE_a0E60szJ5TurUKiShA-mTOcTggg',
    appId: '1:414511917724:ios:e72f246d89601e48cedb59',
    messagingSenderId: '414511917724',
    projectId: 'fire-98df0',
    storageBucket: 'fire-98df0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8-0trzKY-2h9oQ5kBn367DtOk-IXiL70',
    appId: '1:414511917724:web:89ec03e67e4b53c1cedb59',
    messagingSenderId: '414511917724',
    projectId: 'fire-98df0',
    authDomain: 'fire-98df0.firebaseapp.com',
    storageBucket: 'fire-98df0.firebasestorage.app',
  );

}